### ISSUE TITLE
Scrape ComicVine Issue and Volume into Custom Values

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cbanack/comic-vine-scraper#321]
```
Now that we have custom values in ComicRack, we should scrape the Comic Vine 
Issue ID and Volume ID into into those values:

comicvine_issue = xxxxx
comicvine_volume = xxxxx

The first value is really just the CVDB value in a location and format that is 
easier for other script writers to parse.  The second value is also primarly 
there for other script writers, as it will allow them to easily identify which 
comics are in the same series.
```

Original issue reported on code.google.com by `cban...@gmail.com` on 19 May 2013 at 12:11

**Comment by AreFinstad** [comment]
why is this closed when it was never added? 
been using the newest versions of the scraper for ages now and less than 10% of my collection have these entries (i think Mylar added them tho) 
would love for this issue to be opened again if im wrong here and get it added ;)
maybe not remove the option to read the notes entries just yet so people can move own to the other system more easily.

**Comment by cbanack** [comment]
This issue was closed because the feature was added three years ago, exactly as documented here.  If I remember correctly, there is a setting in ComicRack that you have to turn on to enable an extra page of information in the Comic Book info window.  That page has the extra details described here.

 I don't remember exactly what the setting was, but I'm sure it was discussed in the Comic Vine Scraper thread in the ComicRack forums.  Likely on or  around May 2013, when this issue was closed.

Also, please note that I am no longer actively developing Comic Vine Scraper.  I try to fix bugs when I can find the time, but that's it.

**Comment by RogueBurger** [comment]
Preferences -> Behavior -> Application -> Show custom Book fields

When that is checked it will display an extra tab of custom fields when looking at a Book's info.

**Comment by AreFinstad** [comment]
huh..... i have always had that option on, but for some reason most of my collection is missing entries on it yet they where scraped a few months ago.
sorry for the comment then. thought it was a function not in place. i guess ill rescrap my whole collection that is missing them then... this will take hours :(

unsure why it didnt place them in the first place tho. 
maybe its cause those entries dont get saved into the xml file in the cbz file? 
cant see entries for that at all there.

again sorry for the mishap and so on.

**Comment by cbanack** [comment]
Hmm...yeah,  I do seem to remember that a small amount of scraped information does NOT get saved out to the Comic Book file, no matter what settings you have activated (there's a setting you have to turn on in order just to have ANY scraped data saved out to the file). It was a few years ago that we all discussed this, but that does kind of ring a bell in my memory.

In that case, to keep ALL the scraped details, you'd have to manually copy your ComicRack library file (an XML file, I believe) whenever you move your collection to a new computer.  Maybe that's what happened to you?

**Comment by AreFinstad** [comment]
well i didnt think about it at the time. gonna start backing up CR then :D 
most of the data is saved in the xml file. just not custom fields or tags. (categories are tho)
im sure there is more that is not saved but those are the ones i know about. 
a huge pain IMO as it doesnt stay with the file no matter what. 

maybe it can be done with some kind of script. 
but again, im unsure if mylar even reads the xml file itself for that or CR. asked about it on their forums tho :D 
on other notes, i would prob not have bothered collecting without the scraper :D
metadata/info is everything.

**Comment by cbanack** [comment]
You could always try bringing it up on the forums...maybe cYo will change his mind and add that data in to the file format.  I agree that if you save data to the Comic file, it should save ALL data.
