### ISSUE TITLE
Error every time I run scraper

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cbanack/comic-vine-scraper#408]
```
DESCRIBE THE PROBLEM:
I just installed the latest version of Comicrack as well as ComicVine scraper 
and now no matter what I try to scrape I get the same error.


WHAT STEPS WILL REPRODUCE THIS PROBLEM? (Please include the exact name of
the eComic book that you were trying to scrape, if possible.)
1.
2.
3.


WHAT VERSION OF COMICVINESCRAPER ARE YOU USING? 1.0.86



PLEASE PROVIDE ANY ADDITIONAL INFORMATION THAT MAY BE OF USE

```

Original issue reported on code.google.com by `hhav...@hotmail.com` on 18 Mar 2015 at 1:11

Attachments:
* [cvs-debug-log-2015-03-17.txt](https://storage.googleapis.com/google-code-attachments/comic-vine-scraper/issue-408/comment-0/cvs-debug-log-2015-03-17.txt)

**Comment by cbanack** [comment]
Looks like there's nothing left to do here, so closing this issue.
