### ISSUE TITLE
Handle "X of Y covers" better by default

### ISSUE THREAD

**Issue by NordomWhistleklik** [cbanack/comic-vine-scraper#418]
Right now, I believe the default regex is smart enough to ignore "Y covers" (i.e. doesn't think Y is the issue number), however I've come across a significant number of comics that are names in the format "X of Y covers", and the scrapper doesn't know what to do with that X and thinks it's an issue number. Would it be possible to extend the default regex to cover that?

**Comment by cbanack** [comment]
Yes, that won't be too hard.  I'll look into it the next time I'm working on the scraper.   If you see any other common variants of the word "covers" in comic filenames, feel free to add them to this issue.

**Comment by cbanack** [comment]
Fixed in 1.0.93.
