### ISSUE TITLE
Add an autoscrape failed tag

### ISSUE THREAD

**Issue by Verhofin** [cbanack/comic-vine-scraper#436]
If you are scrapping a large amount of new comics and you can´t do it in one go, when you start it again, all the comics, even the ones that failed at autoscrape the first time, will run again making you lose a huge amount of time.

If you add a new tag similar to CVDBSKIP but just informing the the scrapper that auto doesn´t work on that comic and to skip it so as to optimize time and resources, and then after the auto scrapper finishes those comics appear on the manual function.

This way i think its easy to save time and resources and correct me if I´m wrong its not a major change.

**Comment by cbanack** [comment]
Unfortunately I am not actively adding new features to the scraper anymore.  

The best way to avoid the huge amount of time you're losing over this is probably going to be to scrape your comics in smaller batches so you can completely finish each session. 

If for some reason a comic that can't be scraped is still going to get scraped more than once, that's what the CVDVSKIP tag is good for.  Hold down control while clicking skip to automatically add that tag.
