### ISSUE TITLE
Using portions of code.

### ISSUE THREAD

**Issue by hmhrex** [cbanack/comic-vine-scraper#443]
Hey Cory, I'm working on an application that will be using the ComicVine API. I was looking for a use-case in Python, and this is a great example. I was wondering if I could use portions of the API-facing code, with references of course. The biggest part that I'm interested in is checking filenames to match volumes, issues, etc. I wanted to make sure I wasn't infringing on your hard work before I used the same techniques you did.

**Comment by cbanack** [comment]
Please feel free to freely re-use any of the code I've written for the Comic Vine Scraper project.   A small comment mentioning that the code is based on my work would, of course, be appreciated.

Purely out of curiosity (feel free not to answer), what kind of application are you planning to build?

**Comment by hmhrex** [comment]
I don't mind answering privately, but I'll keep it to myself publicly until it's on GitHub. 😄

**Comment by hmhrex** [comment]
**Update:** https://github.com/hmhrex/Tenma

**Comment by theotocopulitos** [comment]
Looks very promising!

**Comment by cbanack** [comment]
Neat!

**Comment by hmhrex** [comment]
@theotocopulitos: Thanks! I've been having a lot of fun with it.

@cbanack: Thanks again for letting me use some of your snippets and ideas!
