### ISSUE TITLE
How to Include Comic Title When Renaming?

### ISSUE THREAD

**Issue by alissongamer** [cbanack/comic-vine-scraper#446]
I would like to know if at the time of renaming the files would have like to include the title of the comic, because here I saved and it only renamed with the series, number and year and I wanted to be included the title too.
If in case this is already possible, please tell me how to do it.

**Comment by cbanack** [comment]
Sorry, comic vine scraper does not rename any files -- it only downloads metadata from the Comic Vine Website.   I don't think it can do what you are looking for.

**Comment by jordanbtucker** [comment]
Please see [Library Organizer](http://comicrack.cyolito.com/forum/13-scripts/11603-library-organizer-version-2-1-11-september-25-2014) for renaming files.

**Comment by alissongamer** [comment]
I was able to solve it using Library Organizer.
Many thanks to all for the help.
