### ISSUE TITLE
Comicvine Scraper not scraping most recent Superman title. Everything else works.

### ISSUE THREAD

**Issue by bfollowell** [cbanack/comic-vine-scraper#450]
As the title says, Superman 35 will not scrape. It just sits there for a really long time before timing out and giving an error that says The Comic Vine online database could not be reached. Every other title I try before or after that works just fine. However, that one title keeps failing over and over and over...

**Comment by jordanbtucker** [comment]
This appears to be the same issue as #449.

**Comment by bfollowell** [comment]
OK, thanks. Yes, I'm certain any title with Superman in the title pulls
down a huge amount of possibilities.

Thanks.

**Comment by cbanack** [comment]
This is indeed the same issue as #449, which means that Comic Vine's engineers will need to fix it.   Fortunately, there's [some evidence](https://comicvine.gamespot.com/forums/bug-reporting-2/api-request-times-out-for-certain-queries-1908981/?page=1#js-message-19478119) that they are now working on it.
