### ISSUE TITLE
ANDing search terms now breaks search

### ISSUE THREAD

**Issue by cbanack** [cbanack/comic-vine-scraper#453]
The fix for issue 349 is no longer needed; that is, the scraper should not AND all of the user's search terms together anymore.

As is explained [here](http://comicrack.cyolito.com/forum/32-news-and-announcements/33534-comic-vine-scraper?start=1530#49152), the ANDing the search terms in not necessary with ComicVine's new search engine, and in fact it breaks searches for hyphenated terms like Golden-age or Spider-man.

**Comment by cbanack** [comment]
Fixed in 1.0.94.

**Comment by grimble65** [comment]
Downloading the latest version (1.0.94) only gives a "zip" file but no "crplugin" can be found anywhere in the package.

**Comment by cbanack** [comment]
You're probably downloading the source code from github (which is packaged up in a zip file).

The crplugin file is in the same place where you originally got it:   on the Comic Vine Scraper homepage, which is at https://cvs.xanatos.ca/.

**Comment by grimble65** [comment]
Just tried to download it from the Scraper homepage and got the same thing, "zip" file.
________________________________
