### ISSUE TITLE
Problem searching for series with "vs" in title

### ISSUE THREAD

**Issue by cbanack** [cbanack/comic-vine-scraper#455]
People seem to be having trouble finding comic series with names like "VS" or "Bionic Man vs Bionic Woman".   This _might_ be a problem with the scraper, i.e. it might be stripping "vs" out or some other interaction with Comic Vine's new search engine.    More details [here](http://comicrack.cyolito.com/forum/32-news-and-announcements/33534-comic-vine-scraper?start=1550#49175).

**Comment by boshuda** [comment]
I did a quick hack, that seems to resolve this.  It does appear that the clean search terms is stripping these off (From cvdb.py in the scripts directory, not the original source code).
`   # 1. clean up the search terms (to make them more palatable to comicvine
   # databases) before our first attempt at searching with them
   search_s = __cleanup_search_terms(search_terms_s, False)
   if search_s == "":
      search_s = search_terms_s`

It does seem to slow things down a touch, but that might just be a result of other changes including the API changes on CV's end

**Comment by cbanack** [comment]
Thanks, I figured it was gonna be something like that.   Easy enough to fix, too.

**Comment by cbanack** [comment]
Fixed in 1.0.95.
