### ISSUE TITLE
Scrape button in comic info with [CVDBSKIP] in notes?

### ISSUE THREAD

**Issue by fieldhouse** [cbanack/comic-vine-scraper#461]
Does anyone know if there is any way (other than going to the Notes tab and deleting the skip text)
`Scraped metadata from ComicVine [CVDBSKIP].`
to allow the Comic Vine Scraper button to work in the Info screen?  Seems like a waste to switch to the info tab, delete the text, then retry the scrape, then ctrl-skip to re-add the text.

If not, no big deal.  Just didn't want to keep going the slow route if I don't have to.

**Comment by cbanack** [comment]
Sadly, there's no shortcut way (like a control-click) to remove the CVDBSKIP tag.   

Back when it was first added, I suggested that people should not use it as part of their regular workflow (i.e. not as something that you flip on any off).   But your mileage may vary, of course.  :)   The original intent was for people to add that tag only to 'weird' comics that are not in the CV database and probably never will be.
