### ISSUE TITLE
Scrapper not accessing Comic Vine Database

### ISSUE THREAD

**Issue by admjim** [cbanack/comic-vine-scraper#465]
I am getting the following when accessing comic vine api through the comic-vine-scraper

Cannot Access Online Database 
The comic vine online database could not be reached.  This may be due to a temporary technical error with the database or there maybe a problem with your internet connection.  
Please try again later.

I am using the most current version 1.0.93.  It does not prompt me to save a log file and I have been unable to find one.  
 
I have tested from my browser with the 
http://comicvine.gamespot.com/api/issues/?api_key=xxxxx
and get the following results I have also verified that the api key is valid.
Current API Usage
You have no current rate limits. Go forth and query
Please advise on what I can do to rectify this issue.

[Comicvine scrape.pdf](https://github.com/cbanack/comic-vine-scraper/files/3612891/Comicvine.scrape.pdf)

**Comment by bodhikun** [comment]
I thought the latest was 1.0.99?

**Comment by cbanack** [comment]
Yup, latest is 1.0.99.   1.0.93 definitely no longer works.   Also, if you
happen to have a very old version of .NET installed on your computer, you
should upgrade that to something more recent.

Cory

**Comment by admjim** [comment]
Thank you Cory that was the issue.  I had tried to install the 1.0.99 version but it did not take and I assumed it had.  Working the midnight shift does weird things to your perception sometimes.  It did take tree attempts to get it to load though twice it onley removed files did not add the new ones back.  

 

Thank you again for your timely help

**Comment by cbanack** [comment]
Yeah, I've seen that problem where the plugin doesn't install properly sometimes.   It's a Comicrack bug; basically if you run the scraper at all before you install the new version, it doesn't take and you need to restart Comicrack to make it work.

Anyway, good that it's working now.
