### ISSUE TITLE
Scraper reporting cannot connect to comicvine

### ISSUE THREAD

**Issue by Krandor1** [cbanack/comic-vine-scraper#471]
Comicvine was having issues earlier today but is back up and API appears to be working but the scraper is still reporting the comicvine database could not be reached.  They may have changed something... again.

**Comment by DrTobogganMD** [comment]
Reporting the same.

**Comment by duckpuppy** [comment]
After running some tests, it looks like they've blocked the ComicVineScraper user agent, or at least changing the UA in the code makes the plugin work again. Not sure if that's intentional or not.

**Comment by cbanack** [comment]
Yeah, I'm guessing they did some kind of security update that causes their servers to be pickier about user agents.   Whatever it is, it definitely does not like Comic Vine's highly irregular custom user agent string, so I've removed it.   It wasn't really doing anything anyhow.    

The fix will be in CVS 1.0.100, which will be available soon.

**Comment by Krandor1** [comment]
Thanks cbanack.  With the comicrack forums being down is this the best way to let you know of issues like this by opening a github issue?

**Comment by cbanack** [comment]
Definitely.

**Comment by Krandor1** [comment]
Perfect,  Thanks for all your work and quick responses.

**Comment by duckpuppy** [comment]
Absolutely, thanks for the quick response to the problem!

**Comment by faethon** [comment]
Thanks for the fix! Great work

**Comment by bradleybowman** [comment]
@cbanack 

I downloaded the latest release, and tried to update the plugin.  ComicRack did its restart, but still showed v1.0.99.  I uninstalled the extension (and in the process, Library Organizer too somehow..).

A fresh install of v1.0.100 prompts for restart, but isn't installed after the restart.  A fresh install of v1.0.99 works.  Are there any logs/system info that I can send you?  

I'm assuming it's working properly for others, so I don't want to waste your time if it's an isolated issue (I'm a rather infrequent user overall, but appreciate the work you've done!)

**Comment by cbanack** [comment]
There's a long-standing bug in ComicRack where if you run the Scraper, and then update the Scraper, the update won't install properly.  Sounds to me like that's what you're seeing.   The easiest thing to do is to immediately install the scraper a second time if it looks like it didn't get installed after the first time.

More precisely, you need to fully shut down ComicRack, re-start it, then immediately install the latest version of the scraper before doing anything else.   (Installing the scraper twice in a row will accomplish this.)

**Comment by bradleybowman** [comment]
@cbanack 

With v1.0.99 installed, and following your method exactly, I was able to get the update to v1.0.100 to complete.  I had not run the scraper prior to attempting the first install, so I'm not sure what got me stuck in that state.

At any rate, that resolves it.  Apologies for re-reporting a known issue, I should've used the search first.

**Comment by tdisalvo** [comment]
Many thanks for keeping this up.  Do you have a Paypal for donations?

**Comment by cbanack** [comment]
Yes I do:

https://github.com/cbanack/comic-vine-scraper/wiki/Support-the-Project

But these days I am basically just "keeping the lights on" with this project, so I'm not really expecting any donations.   Your thanks is worth a lot, though.
