### ISSUE TITLE
download host is not responding

### ISSUE THREAD

**Issue by BigChaps** [cbanack/comic-vine-scraper#477]
There seems to be a problem accessing your download link, the website is not responding. I tested previous version download links and it seems to be related to the site rather than just this link.

Just an additional note, I really appreciate your work. It has helped me enjoy my collection like never before...

**Comment by cbanack** [comment]
Ah yes, I woke up this morning to discover that the router for that server died overnight.   Should be fixed now, if not let me know...

And you are quite welcome, I am always happy to hear that people are enjoying the scraper!
