### ISSUE TITLE
The Comic Vine online database could not be reached

### ISSUE THREAD

**Issue by namanix** [cbanack/comic-vine-scraper#481]
When I try to scrape comics with the scraper it gives this message.
I don't really know what I can do to fix this. I hope someone can help me with this issue.

**Comment by ralonsoj** [comment]
I have problems with the connection, too.

**Comment by AlexanderTurnowsky** [comment]
same here on my side. Hopefully this is only a temp. issue.

**Comment by cbanack** [comment]
It looks like the Comic Vine API (i.e. the servers that have all the comic book info) are currently broken.  I've emailed Comic Vine to let them know.   If this is anything like previous occasions when this has happened, I don't imagine it will take very long for them to fix it.

At that point, the scraper should start working again.

**Comment by namanix** [comment]
It seems to work again for me now. How about you @ralonsoj @AlexanderTurnowsky @cbanack ?

**Comment by ralonsoj** [comment]
Yes, it works again :P

**Comment by cbanack** [comment]
Probably they just needed to reboot their servers. 😁
