### ISSUE TITLE
The Comic Vine online database could not be reached

### ISSUE THREAD

**Issue by SonOfDiablo** [cbanack/comic-vine-scraper#483]
Hello,

It seems there is an issue with the ComicVine database.

I saw this issue from February https://github.com/cbanack/comic-vine-scraper/issues/481 however the forum post mentions that the issue was resolved.
I checked the forum (briefly) but it doesn't seem to be the most active forum.. 

Thus this issue, is the problem with ComicVine? has the API endpoints been moved? Something I have to do locally?

I'm using v1.0.100

**Comment by cbanack** [comment]
The API is working for me right now, though it is possible that it went down for a while when you were having problems.   Is the scraper working correctly now?

If not, the culprit might be your network, like a firewall or something, that's blocking access to https://comicvine.gamespot.com/api/.

**Comment by SonOfDiablo** [comment]
I tried turning off my firewall and still getting the same error message.

I should also mention that I installed the script by extracting the .crplugin instead of installing it normally through ComicRack, as ComicRack doesn't wanna let me install scripts normally, not sure if that could have any effect?

I also just tried to couple together the following: 
```
http://comicvine.gamespot.com/api/search/?api_key=APIkey123&format=xml&limit=100&resources=volume&field_list=name,start_year,publisher,id,image,count_of_issues&query=Deadpool
``` 
which works in my browser (and wget if I provide a browser UA, otherwise I get a 403 forbidden error)

**Comment by cbanack** [comment]
Hmm, well if the API is working, I would think the unusual way you installed it is the next most likely culprit. 

You could try getting the error as usual, and then press ctrl-shift-L while the comic vine scraper window is open.   This will let you save out a log, which might provide you with some more insight.  (It might be ctrl-alt-L, I can't remember off the top of my head).

**Comment by SonOfDiablo** [comment]
... I feel really dumb now, appears I copied in the wrong API key.

Got it working now, thank you for the log tip, helped narrow down the issue once I knew it was a 401 Unauthorized error
