### ISSUE TITLE
Removed Comic Vine Script. Files are deleted from c:\Users\carlr\AppData\Roaming\cYo\ComicRack\Scripts\ but still showing in ComicRack Toolbar

### ISSUE THREAD

**Issue by Bugmaniac71** [cbanack/comic-vine-scraper#489]
I have removed Comic Vine Script to perform teh update to .101. Files are deleted from c:\Users\carlr\AppData\Roaming\cYo\ComicRack\Scripts\ but it's still showing in ComicRack Toolbar after a restart. If I install an older version for testing (say .98) then the script manager says that its onstalle dok but the version in teh toolbar still says 100. Any thoughts please as its preventing the upgrade to 101 and the CV fix.

Regards
Carl.

**Comment by cbanack** [comment]
This is a bug in how ComicRack handles upgrades to plugins.   I see it whenever I update the Comic Vine Scraper.

To fix the problem, all you need to do is **fully** shutdown and restart ComicRack after you remove the old version of Comic Vine Scraper.  Most likely, you aren't REALLY shutting it down (I believe it stays alive in your task bar.)   

One way to guarantee that you've restarted ComicRack (as silly as it sounds) is to reboot windows.

**Comment by Bugmaniac71** [comment]
Ah I see. Sorted now, reboot of windows fixed it many thanks.
