### ISSUE TITLE
CVS Keeps suggesting Green Lantern: War Journal for suggested series....over 1000 inaccurate replacements so far...

### ISSUE THREAD

**Issue by shanezuspan** [cbanack/comic-vine-scraper#493]
Baffled by how this is happening... New comics from GetComics or Mylar. I have the "write to file" option selected in the main comicrack settings. And I usually convert to cbz pretty early on in the process. I just cant imagine how, even writing file data, it comes up with the same incorrect Green Lantern: War Journal series to write over and over. It's like there's a "if no name exists, use series Green Lantern: War Journal" config option... something has to trigger that as a comicvine match somehow... again totally befuddled. Have tried to "clear data" but the only way is to let the scraper run and prompt on every new comic so I can go "back", search again, and select the correct comic. The "search again" usually finds a list of exact or very similar options. 

![p451kz2jj8qb1 (1)](https://github.com/cbanack/comic-vine-scraper/assets/55251478/f6dae73f-8f66-4eef-aee0-e7101e881a9b)

**Comment by cbanack** [comment]
Well, the Comicvine Scraper uses the filename of the comic book file to determine which series it most likely belongs to (that's how it gives you a list of series to choose from.)   What are the full files names of a couple of the comics that are being identified as Green Lantern: War Journal?

The series chosen for a comic book can also be manually forced in two ways.   The first way is by creating a 'cvinfo' file in the same folder as your comic files (that is what it looks like might be happening here), and the second way is if there is a "CVDB" tag added to the Tags or Notes (typically added from a previous scrape attempt).

Both features are described [here](https://github.com/cbanack/comic-vine-scraper/wiki/CVINFO-and-CVDB-tags).   First thing to do is make sure you're not accidentally using either of them.

**Comment by shanezuspan** [comment]
Ok will check and see if there's a rogue cvinfo file maybe hanging out in the root folder. All the file names are outlined in red in the middleish column in the image on the post. Which is why this is so weird, as the file names are all accurate to the content. Thanks for the speedy reply on a holiday!

**Comment by shanezuspan** [comment]
Huzzah! Yep, a lone cvinfo file in the main directory where I usually place my individual comics to be renamed/organized...
https://comicvine.gamespot.com/green-lantern-war-journal/4050-153625/

Thanks so much for the help! That has been driving me nuts on and off for a year now!

**Comment by cbanack** [comment]
Nice, glad it was an easy fix.

Happy New Year!
