### ISSUE TITLE
Can’t install CV Scraper 1.0.102

### ISSUE THREAD

**Issue by unclerandy1969** [cbanack/comic-vine-scraper#495]
I don’t know why, but for some reason I cannot install the latest (final) update of CV Scraper in CE. The only thing it seems to write in the scripts folder is a few image files. Have tried several times unsuccessfully and had to reinstall older version. (Actually I think I just ended up copying all the contents from the original CR Scraper folder.) A few times I tried installing, restarting and it would continue to want to reinstall and restart over and over…

**Comment by cbanack** [comment]
I believe you need to: 1) uninstall CV Scraper, then 2) completely shutdown ComicRack, then 3) restart ComicRack, then 4) install the new version CV Scraper.

The hard part is #2, I think ComicRack will keep running in the task tray / background even after you close the window, so you have to make sure it is completely shut down.   Just close the window might not be enough.    (One way to be sure it is fully shutting down is to restart your computer.)

This is a longstanding bug in ComicRack, unfortunately.

**Comment by unclerandy1969** [comment]
This worked. Thanks for the help.
