### ISSUE TITLE
Add Format to scarped data

### ISSUE THREAD

**Issue by fantomdew** [cbanack/comic-vine-scraper#499]
I was wondering if there were any plans to add Format to the data that is scraped?

**Comment by cbanack** [comment]
Sorry, but I stopped active development on the Scraper years ago.  I'm only keeping it working for the people that still use it, but no new features. 

If you or someone you know were to make the needed modifications to the code (in the form of a git pull request) I would review it and consider compiling it into a new version of the Scraper.
